Provider: 'AlpacaPaperTrading'
StakeClient:
  Username: 'erwan.joly@gmail.com'
  Password: 'PBC0s3k!$uPQqCahoJ@SvQTGkrZlSfo#3dRy3s8Aa#h82*oZWl'
AlpacaPaperTradingClient:
  ApiKey: 'PKU402OXAPU2GPG15JJ8'
  ApiSecret: 'WIA2V1qQQRRBWgBuj8zue4d/xbVH6OCs61ALkAyk'